Added deleteTemplate method
CCphobia/Hermes pull request #8
Opened 2019-12-22 09:16 UTC by CCphobia

#4 Added deleteTemplate method in repo and service and wrote respective test methods.
Adjusted testAddTemplate to avoid problems with hibernate having problems with @lob object.
Renamed testGetTemplateShouldThrowNoSuchEntityExceptioan() to properly represent tested problem

2019-12-22 11:15 UTC, Burdzi0 commented on src/main/java/pwr/asi/java/hermes/services/TemplateService.java
> +        if (template.isPresent()) {
Use `ifPresentOrElse`

2019-12-23 15:51 UTC, KarolKalbarczyk reviewed
in testDeleteTemplateByTitle add assert throw for trying to get Template "A"

2019-12-23 16:23 UTC, Burdzi0 requested changes
Change to `ifPresentOrElse()`, the rest is up to You

2019-12-23 16:23 UTC, Burdzi0 commented on src/main/java/pwr/asi/java/hermes/services/TemplateService.java
> +        if (template.isPresent()) {
Please use `ifPresentOrElse()`

2019-12-23 16:23 UTC, Burdzi0 commented on src/test/java/pwr/asi/java/hermes/services/TemplateServiceTest.java
> +        assertThat(templateService.getTemplate(template.getTitle()).equals(template));
Use `isEqualTo` as above or change the above to use `equals` as here

2019-12-23 16:23 UTC, Burdzi0 commented on src/main/java/pwr/asi/java/hermes/services/TemplateService.java
> +        var template = templateRepository.getByTitle(title);
Maybe would it be nice to use `final`?

2019-12-23 16:27 UTC, Burdzi0 commented
Also read: https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
I'm pretty sure You need some keyword before the issue number to close it

2019-12-30 22:43 UTC, Burdzi0 approved these changes

2020-01-01 02:13 UTC, merged